#pragma once
// On-device ECDSA (P-256) firmware-signature verification (ESP32 only).
// Uses the mbedtls bundled with Arduino-ESP32; the public key is baked in
// at build time (ota_public_key.h, generated by scripts/sign_firmware.py).

#if defined(ESP32)

#include <mbedtls/ecdsa.h>
#include <mbedtls/sha256.h>
#include "ota_public_key.h"

/** Verify an ECDSA P-256 signature (64-byte raw r||s) over a 32-byte
 *  SHA-256 digest against the baked-in public key. Returns true if valid. */
inline bool hcs_ota_verify_signature(const uint8_t* digest, const uint8_t* sig) {
  mbedtls_mpi r, s;
  mbedtls_ecp_group grp;
  mbedtls_ecp_point q;
  mbedtls_mpi_init(&r);
  mbedtls_mpi_init(&s);
  mbedtls_ecp_group_init(&grp);
  mbedtls_ecp_point_init(&q);

  bool ok = false;
  if (mbedtls_ecp_group_load(&grp, MBEDTLS_ECP_DP_SECP256R1) == 0 &&
      mbedtls_ecp_point_read_binary(&grp, &q, HCS_OTA_PUBKEY, 65) == 0 &&
      mbedtls_mpi_read_binary(&r, sig, 32) == 0 &&
      mbedtls_mpi_read_binary(&s, sig + 32, 32) == 0) {
    ok = (mbedtls_ecdsa_verify(&grp, digest, 32, &q, &r, &s) == 0);
  }

  mbedtls_mpi_free(&r);
  mbedtls_mpi_free(&s);
  mbedtls_ecp_point_free(&q);
  mbedtls_ecp_group_free(&grp);
  return ok;
}

#endif  // ESP32
