#!/usr/bin/env python3
"""ECDSA (P-256) firmware signing for Home Climate System OTA.

Each release ships a ``.bin`` alongside a ``.sig`` (64-byte raw r||s ECDSA
signature over the SHA-256 of the image). The board streams the image to the
OTA partition, hashes it, and verifies the signature against the baked-in
public key before booting the new image — so a tampered / MITM'd image is
rejected on device.

Usage:
    python3 scripts/sign_firmware.py gen-key
        -> ota_secret.key (PRIVATE — never commit) + ota_public.pem +
           firmware/include/ota_public_key.h (baked into firmware)

    python3 scripts/sign_firmware.py sign <file.bin>
        -> <file.bin>.sig

    python3 scripts/sign_firmware.py verify <file.bin> <file.bin.sig>
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
from cryptography.exceptions import InvalidSignature

REPO_ROOT = Path(__file__).resolve().parent.parent
PUBKEY_H = REPO_ROOT / "firmware" / "include" / "ota_public_key.h"


def gen_key() -> None:
    sk = ec.generate_private_key(ec.SECP256R1())
    sk_pem = sk.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    pk = sk.public_key()
    pk_pem = pk.public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    (REPO_ROOT / "ota_secret.key").write_bytes(sk_pem)
    (REPO_ROOT / "ota_public.pem").write_bytes(pk_pem)

    # Uncompressed point: 0x04 || X(32) || Y(32)
    nums = pk.public_numbers()
    raw = b"\x04" + nums.x.to_bytes(32, "big") + nums.y.to_bytes(32, "big")

    header = (
        "#pragma once\n"
        "// Baked-in ECDSA P-256 public key (uncompressed 65-byte point).\n"
        "// Generated by scripts/sign_firmware.py gen-key — regenerate + rebuild\n"
        "// if the private key is rotated.\n"
        "static const unsigned char HCS_OTA_PUBKEY[65] = {\n"
    )
    for i in range(0, len(raw), 12):
        header += "    " + ", ".join(f"0x{b:02x}" for b in raw[i : i + 12]) + ",\n"
    header += "};\n"

    PUBKEY_H.write_text(header)
    print(f"wrote ota_secret.key (KEEP PRIVATE), ota_public.pem, {PUBKEY_H}")


def _load_key() -> ec.EllipticCurvePrivateKey:
    # CI signs with the key from the OTA_SIGNING_KEY secret; locally it reads
    # the key file written by `gen-key`.
    pem = os.environ.get("OTA_SIGNING_KEY")
    if pem:
        return serialization.load_pem_private_key(pem.encode(), password=None)
    return serialization.load_pem_private_key(
        (REPO_ROOT / "ota_secret.key").read_bytes(), password=None
    )


def sign(bin_path: str) -> None:
    sk = _load_key()
    data = Path(bin_path).read_bytes()
    der = sk.sign(data, ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(der)
    raw = r.to_bytes(32, "big") + s.to_bytes(32, "big")
    Path(bin_path + ".sig").write_bytes(raw)
    print(f"signed {bin_path} -> {bin_path}.sig ({len(raw)} bytes)")


def verify(bin_path: str, sig_path: str) -> None:
    pk = serialization.load_pem_public_key(
        (REPO_ROOT / "ota_public.pem").read_bytes()
    )
    data = Path(bin_path).read_bytes()
    raw = Path(sig_path).read_bytes()
    if len(raw) != 64:
        print("FAIL — signature must be 64 bytes")
        sys.exit(1)
    from cryptography.hazmat.primitives.asymmetric.utils import (
        encode_dss_signature,
    )

    r = int.from_bytes(raw[:32], "big")
    s = int.from_bytes(raw[32:], "big")
    der = encode_dss_signature(r, s)
    try:
        pk.verify(der, data, ec.ECDSA(hashes.SHA256()))
        print("OK — signature valid")
    except InvalidSignature:
        print("FAIL — signature invalid")
        sys.exit(1)


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "gen-key":
        gen_key()
    elif cmd == "sign" and len(sys.argv) == 3:
        sign(sys.argv[2])
    elif cmd == "verify" and len(sys.argv) == 3:
        verify(sys.argv[2], sys.argv[2] + ".sig")
    else:
        print(__doc__)
        sys.exit(2)


if __name__ == "__main__":
    main()
